### ISSUE TITLE
libssh build failing

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1161]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

@cryptomilk - can you please take a look.

**Comment by inferno-chromium** [comment]
@cryptomilk - i see still failures even after your fix and my minor fix.

Can you please send a pull request with fix for this

```
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -Iinclude/ /src/libssh/tests/fuzz/ssh_server_fuzzer.cpp -o /out/libssh_server_fuzzer -lFuzzingEngine ./src/libssh.a -Wl,-Bstatic -lcrypto -lz -Wl,-Bdynamic
/src/libssh/tests/fuzz/ssh_server_fuzzer.cpp:27:10: fatal error: 
      'libssh/libssh.h' file not found
#include <libssh/libssh.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
fuzzers build failed.
```
Please verify build works using python infra/helper.py build_fuzzers libssh

**Comment by cryptomilk** [comment]
This, should be fixed now?

**Comment by inferno-chromium** [comment]
@cryptomilk - still fails on same error.

Can you please try locally with "python infra/helper.py build_fuzzers libssh"

**Comment by cryptomilk** [comment]
I fixed it and didn't push it to master. It should be fixed now! :-)

**Comment by inferno-chromium** [comment]
@cryptomilk - now running into this error. would really appreciate if you can please verify locally with build_fuzzers command. we are a small team with limited debugging cycles :(

```
[100%] Built target libsshpp
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -Iinclude/ /src/libssh/tests/fuzz/ssh_server_fuzzer.cpp -o /out/libssh_server_fuzzer -lFuzzingEngine ./src/libssh.a -Wl,-Bstatic -lcrypto -lz -Wl,-Bdynamic
/src/libssh/tests/fuzz/ssh_server_fuzzer.cpp:27:10: fatal error: 
      'libssh/libssh.h' file not found
#include <libssh/libssh.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
fuzzers build failed.
```

**Comment by inferno-chromium** [comment]
@cryptomilk - libssh fuzzing is down for a month. this should be an easy fix, can you please patch this in libssh repo. thanks a lot!

**Comment by cryptomilk** [comment]
With #1230 it should be fixed, at least it built successfully running locally here.
