### ISSUE TITLE
qubes-os: bad build, partial instrumentation

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1332]
Has been detected after lading #838

https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #5: INFO: performing bad build checks for /workspace/out/address/libqubes-rpc-filecopy.
Step #5: Broken fuzz targets (1):
Step #5: libqubes-rpc-filecopy:
Step #5: BAD BUILD: the target seems to have only partial coverage instrumentation.
Step #5: ERROR: 100% of fuzz targets seem to be broken. See the list above for a detailed information.
```

**Comment by Dor1s** [comment]
//cc @jpouellet, @paraschetal are you planning to work on fuzzing / OSS-Fuzz integration for qubes-os?

It's been a while since the initial integration and it does not look like we have any positive progress with qubes-os project: https://github.com/google/oss-fuzz/commits/master/projects/qubes-os

Please let us know if you're planning to do contribute more. Otherwise, we'll disable the project.

**Comment by jpouellet** [comment]
Unless @marmarek says otherwise, feel free to disable. AFAIK this is not a priority for anyone right now.

My sincere thanks for running oss-fuzz. We may not be have ended up taking advantage directly, but we do definitely benefit indirectly from the impact you have on the ecosystem at large. Cheers :beers:

**Comment by Dor1s** [comment]
@marmarek, glad to hear that!

**Comment by inferno-chromium** [comment]
fixed

**Comment by Dor1s** [comment]
This is still an issue: https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #5: INFO: performing bad build checks for /workspace/out/address/input-proxy-receiver_fuzzer.
Step #5: INFO: performing bad build checks for /workspace/out/address/libqubes-rpc-filecopy.
Step #5: Broken fuzz targets (1):
Step #5: libqubes-rpc-filecopy:
Step #5: BAD BUILD: the target seems to have only partial coverage instrumentation.
Step #5: ERROR: 50% of fuzz targets seem to be broken. See the list above for a detailed information.
```

**Comment by Dor1s** [comment]
@marmarek, it's been 2 months since your comment https://github.com/google/oss-fuzz/issues/1332#issuecomment-382187968

qubes-os project integration definitely needs some care and maintenance. Otherwise, we seem to be wasting CPU cycles on it, e.g. see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9002

**Comment by marmarek** [comment]
The target causing problems before was removed (see above), this is a different problem. I'll look into it next week when I'll be back at work.

**Comment by Dor1s** [comment]
Sure, I could create a separate issue, but my main point was to highlight that the project either needs maintenance or will be removed. Last time we agreed that it would be maintained, but it doesn't look like anything has been done in that matter.

**Comment by marmarek** [comment]
I've looked at it, and I don't see what is wrong. According to the build log, all relevant compile flags are used (CFLAGS as provided by build env). The thing is, the resulting binary have 166 calls to __ubsan (counted using that egrep call in bad_build_check), but the threshold is 170. Is the build really broken, or is it a false positive?
BTW this is a problem with a different fuzzing target than 2 months ago, the non-maintained one was removed then.

**Comment by Dor1s** [comment]
166 calls to __ubsan means that there is only one single place in your program that has a UBSan instrumentation hook added. The other 165 calls are from the runtime itself. We should not be spending cycles for fuzzing a program that has a potential of finding just 1 UBsan error.

**Comment by marmarek** [comment]
Does it make sense to disable this particular sanitizer for now but still use others? Is it possible to _automatically_ enable it later when the code will grow and UBsan would make more sense here?

**Comment by Dor1s** [comment]
> Does it make sense to disable this particular sanitizer for now but still use others? 

Yes, that sounds like an option to me!

> Is it possible to automatically enable it later when the code will grow and UBsan would make more sense here?

No.
