### ISSUE TITLE
Public corpus download started producing empty zip files today (which breaks upstream CI) 😞

### ISSUE THREAD

**Issue by hartwork** [google/oss-fuzz#14045]
Hi!

The public corpus download for Expat started producing empty zip files today which [breaks my upstream fuzzing regression CI for Expat](https://github.com/libexpat/libexpat/actions/runs/17919040923). For proof:

```console
# cd "$(mktemp -d)"

# wget -q -O corpus.zip https://storage.googleapis.com/expat-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/expat_xml_parse_fuzzer_UTF-8/public.zip

# ls -l
total 4.0K
-rw-r--r-- 1 user123 user123 22 22. Sep 14:05 corpus.zip

# file corpus.zip 
corpus.zip: Zip archive data (empty)

# unzip corpus.zip 
Archive:  corpus.zip
warning [corpus.zip]:  zipfile is empty

# ls -l
total 4
-rw-r--r-- 1 user123 user123 22 22. Sep 14:05 corpus.zip
```

Is this known? Could it be fixed?

Thanks in advance! 🙏

**Comment by catenacyber** [comment]
Same here for Suricata

**Comment by catenacyber** [comment]
Would you know about this @DavidKorczynski ?

**Comment by hartwork** [comment]
uriparser is also affected (https://storage.googleapis.com/uriparser-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/uriparser_uri_dissect_query_malloc_fuzzer/public.zip). My guess is that *all* projects are affected? I hope there are backups…

**Comment by evverx** [comment]
Looks like it was fixed somehow. My stuff started working again yesterday as far as I can tell.

**Comment by hartwork** [comment]
@evverx thanks for the notification! I would close this issue as "no longer an issue" unless something is still not working for @catenacyber?

**Comment by catenacyber** [comment]
Ok for closing
