### ISSUE TITLE
[CIFuzz] Affected fuzzers won't work with go projects

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#5337]
This wont work with projects compiled using go projects because they do not create a proper summary.json file.
Compare http://storage.googleapis.com/oss-fuzz-coverage/suricata/reports/20210309/linux/summary.json (rust project)
to http://storage.googleapis.com/oss-fuzz-coverage/gonids/reports/20210309/linux/summary.json (go project).

**Comment by jonathanmetzman** [comment]
@catenacyber How much effort do you think it would be to support this format?

**Comment by catenacyber** [comment]
Do you mean to update the format that was described there https://github.com/google/oss-fuzz/issues/2817#issuecomment-725008083 ?

If so, I think this is just about changing gocovsum

**Comment by catenacyber** [comment]
We do not have info about branches and I do not know what `instantiations` are

**Comment by jonathanmetzman** [comment]
> This wont work with projects compiled using go projects because they do not create a proper summary.json file.
> Compare http://storage.googleapis.com/oss-fuzz-coverage/suricata/reports/20210309/linux/summary.json (rust project)
> to http://storage.googleapis.com/oss-fuzz-coverage/gonids/reports/20210309/linux/summary.json (go project).

Actually I'm wrong about this.
it's not really summary.json that I need, it's the per-target json files.
For example: 
http://storage.googleapis.com/oss-fuzz-coverage/go-ethereum/fuzzer_stats/20210309/fuzz_pairing.json

But I assume that the fact that all these files (target jsons and summary.json) are empty means something in go cov is broken?

**Comment by jonathanmetzman** [comment]
> For gonids and go-dns, I get
> 
> ```
> # runtime/cgo
> cgo: exec gcc: exec: "gcc": executable file not found in $PATH
> ```
> 
> Was gcc part of the things you removed @jonathanmetzman ?
> Could we put it back ?
> 
> I get the reports ok after running `apt install -y gcc` in the docker base-runner

This seems like a separate issue right?
I think I recently did remove gcc. Why is it needed for coverage? I'd like to not add it back since it increases image size too much.
I don't know how go coverage works, but it seems like there should be a workaround.

**Comment by catenacyber** [comment]
There are indeed 2 issues :
- golang coverage was broken after gcc removal, should be fixed by #5377
- golang coverage summary is not in the right format, should be fixed by #5346
(and there was the report formatting of merged coverages with go 1.16 modules which got fixed by #5321)

Is it good to you ?

PS : for CIFuzz, in addition to restricting the fuzz targets, you should also restrict the corpus to the inputs covering the modified files

**Comment by jonathanmetzman** [comment]
This still doesn't work btw.
Here's logs from a [prometheus cifuzz run](https://github.com/prometheus/prometheus/runs/2250852096?check_suite_focus=true):
```
Loading json from url https://storage.googleapis.com/oss-fuzz-coverage/prometheus/fuzzer_stats/20210401/fuzzParseExpr.json failed with: Expecting value: line 1 column 1 (char 0).
```
That file (https://storage.googleapis.com/oss-fuzz-coverage/prometheus/fuzzer_stats/20210401/fuzzParseMetricSelector.json) is empty

**Comment by jonathanmetzman** [comment]
Though another go project myanmar-tools has this file for gs://oss-fuzz-coverage/myanmar-tools/fuzzer_stats/20210402/zawgyi_detector_fuzz_target.json
and affected fuzzers seems to work there: https://github.com/google/myanmar-tools/runs/2240068992?check_suite_focus=true

Maybe coverage is broken for prometheus even though it's not marked as such on https://oss-fuzz-build-logs.storage.googleapis.com/

**Comment by catenacyber** [comment]
Getting this error with prometheus running `python infra/helper.py coverage --fuzz-target fuzzParseExpr --corpus-dir dummydir prometheus`

```
failed to parse profiles: inconsistent NumStmt: changed from 2 to 1
```

**Comment by catenacyber** [comment]
It looks like generated coverage for `promql/parser/generated_parser.y.go` is wrong
```
github.com/prometheus/prometheus/promql/parser/generated_parser.y.go:178.0,180.0 2 1
github.com/prometheus/prometheus/promql/parser/generated_parser.y.go:179.0,178.0 2 1
github.com/prometheus/prometheus/promql/parser/generated_parser.y.go:176.0,178.0 1 0
github.com/prometheus/prometheus/promql/parser/generated_parser.y.go:178.0,180.0 1 1
```
I think it looks like a golang bug...

**Comment by catenacyber** [comment]
Submitted https://github.com/golang/go/issues/45361

**Comment by jonathanmetzman** [comment]
I think this is fixed.
