### ISSUE TITLE
False negative issue, prematurely published

### ISSUE THREAD

**Issue by rlohning** [google/oss-fuzz#5604]
Hi,

[30973](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30973) was incorrectly marked "Verified" and thus published. Could you please reset it to "New (Open)" and "Only users with Commit permission or issue reporter may view".

Thanks,
Robert

**Comment by inferno-chromium** [comment]
Done!

**Comment by rlohning** [comment]
The issue is still publicly visible. Could you please correct this?

**Comment by inferno-chromium** [comment]
> The issue is still publicly visible. Could you please correct this?

Done!

**Comment by rlohning** [comment]
Thank you.
