### ISSUE TITLE
Duplicate bug report for fixed issue is created three days after fix

### ISSUE THREAD

**Issue by MarcoFalke** [google/oss-fuzz#5821]
Timeline:
* May 18th: Initial bug reported: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34434
* May 20th: Our fix is verified: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34434#c3
* May 23rd: Erroneous duplicate issue is filed: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34611

Looks like it used some stale code or fuzz binary?

**Comment by evverx** [comment]
Looks like https://github.com/google/oss-fuzz/issues/4083. Generally It happens all the time (especially when new projects have been integrated). `builds_per_day: 4` helps a bit in the sense that duplicates like that get closed faster but unfortunately they are still reported.

**Comment by inferno-chromium** [comment]
I don't think this is #4083 

This bug is still reproducing with this testcase, so could be just a variant of the first one. Are you sure it does not crash with latest target.
[2021-05-24 14:28:12 UTC] oss-fuzz-linux-zone3-host-8fhv-10: Progression task finished: still crashes on latest revision r202105240624.

**Comment by MarcoFalke** [comment]
Yes, I am 99% sure this bug is fixed. I reran the progression one more time and now it prints:


```
[2021-05-28 02:13:04 UTC] oss-fuzz-linux-zone7-host-pq1z-0: Progression task finished: still crashes on latest revision r202105250624.
```

Note the day May 28th, which will be 3 days in the future.

**Comment by MarcoFalke** [comment]
Today is May 25th

**Comment by inferno-chromium** [comment]
> Yes, I am 99% sure this bug is fixed. I reran the progression one more time and now it prints:
> 
> ```
> [2021-05-28 02:13:04 UTC] oss-fuzz-linux-zone7-host-pq1z-0: Progression task finished: still crashes on latest revision r202105250624.
> ```
> 
> Note the day May 28th, which will be 3 days in the future.

r202105250624 is the more important (we will see what is going wrong with bot clock), which means today's build still crashes on it. i have never seen clusterfuzz/oss-fuzz being wrong on reproducing a bug, so please try it locally.

**Comment by MarcoFalke** [comment]
I couldn't reproduce with a local build. I'll try with https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-bugs in a fresh vm next.

**Comment by MarcoFalke** [comment]
Using `infra`, I found that the *initial* crash input does *not* crash, only the *minimized* one crashes. Locally none reproduce.

<details><summary>Full output:</summary>

```
# md5sum ./*id*
401fe1b854d0f321ff96485f9a48dc68  ./4a64c252-1cc2-48d3-9979-47050b0f8e05?testcase_id=6289089386119168
16ad30603f26dc637ae7cb45ff3f5e47  ./6e13b65b-6648-47dd-b1ff-b6f005ecf8dc?testcase_id=6289089386119168
16ad30603f26dc637ae7cb45ff3f5e47  ./download?testcase_id=6289089386119168



# python infra/helper.py reproduce $PROJECT_NAME coins_view ./4a64c252-1cc2-48d3-9979-47050b0f8e05\?testcase_id\=6289089386119168 
Running: docker run --rm --privileged -i -v /root/oss-fuzz/build/out/bitcoin-core:/out -v '/root/oss-fuzz/4a64c252-1cc2-48d3-9979-47050b0f8e05?testcase_id=6289089386119168:/testcase' -t gcr.io/oss-fuzz-base/base-runner reproduce coins_view -runs=100
+ FUZZER=coins_view
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer coins_view -runs=100 /testcase
/out/coins_view -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 470330160
INFO: Loaded 1 modules   (177730 inline 8-bit counters): 177730 [0x55bf3959eb68, 0x55bf395ca1aa), 
INFO: Loaded 1 PC tables (177730 PCs): 177730 [0x55bf395ca1b0,0x55bf398805d0), 
/out/coins_view: Running 1 inputs 100 time(s) each.
Running: /testcase
Executed /testcase in 366 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***




# python infra/helper.py reproduce $PROJECT_NAME coins_view ./6e13b65b-6648-47dd-b1ff-b6f005ecf8dc\?testcase_id\=6289089386119168 
Running: docker run --rm --privileged -i -v /root/oss-fuzz/build/out/bitcoin-core:/out -v '/root/oss-fuzz/6e13b65b-6648-47dd-b1ff-b6f005ecf8dc?testcase_id=6289089386119168:/testcase' -t gcr.io/oss-fuzz-base/base-runner reproduce coins_view -runs=100
+ FUZZER=coins_view
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer coins_view -runs=100 /testcase
/out/coins_view -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 477890002
INFO: Loaded 1 modules   (177730 inline 8-bit counters): 177730 [0x55c22d9d9b68, 0x55c22da051aa), 
INFO: Loaded 1 PC tables (177730 PCs): 177730 [0x55c22da051b0,0x55c22dcbb5d0), 
/out/coins_view: Running 1 inputs 100 time(s) each.
Running: /testcase
coins_view: test/fuzz/coins_view.cpp:240: auto coins_view_fuzz_target(FuzzBufferType)::(anonymous class)::operator()() const: Assertion `MoneyRange(tx_fee_out)' failed.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==13==ERROR: AddressSanitizer: ABRT on unknown address 0x00000000000d (pc 0x7f65ab3e3438 bp 0x55c22cf45420 sp 0x7ffcd39ac5c8 T0)
SCARINESS: 10 (signal)
    #0 0x7f65ab3e3438 in raise (/lib/x86_64-linux-gnu/libc.so.6+0x35438)
    #1 0x7f65ab3e5039 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37039)
    #2 0x7f65ab3dbbe6  (/lib/x86_64-linux-gnu/libc.so.6+0x2dbe6)
    #3 0x7f65ab3dbc91 in __assert_fail (/lib/x86_64-linux-gnu/libc.so.6+0x2dc91)
    #4 0x55c22bd410ab in coins_view_fuzz_target(Span<unsigned char const>)::$_12::operator()() const /src/bitcoin-core/src/test/fuzz/coins_view.cpp:240:17
    #5 0x55c22bd2eb4f in void CallOneOf<coins_view_fuzz_target(Span<unsigned char const>)::$_10, coins_view_fuzz_target(Span<unsigned char const>)::$_11, coins_view_fuzz_target(Span<unsigned char const>)::$_12, coins_view_fuzz_target(Span<unsigned char const>)::$_13, coins_view_fuzz_target(Span<unsigned char const>)::$_14, coins_view_fuzz_target(Span<unsigned char const>)::$_15, coins_view_fuzz_target(Span<unsigned char const>)::$_16>(FuzzedDataProvider&, coins_view_fuzz_target(Span<unsigned char const>)::$_10, coins_view_fuzz_target(Span<unsigned char const>)::$_11, coins_view_fuzz_target(Span<unsigned char const>)::$_12, coins_view_fuzz_target(Span<unsigned char const>)::$_13, coins_view_fuzz_target(Span<unsigned char const>)::$_14, coins_view_fuzz_target(Span<unsigned char const>)::$_15, coins_view_fuzz_target(Span<unsigned char const>)::$_16) /src/bitcoin-core/src/./test/fuzz/util.h:47:34
    #6 0x55c22bd2d8fa in coins_view_fuzz_target(Span<unsigned char const>) /src/bitcoin-core/src/test/fuzz/coins_view.cpp:192:9
    #7 0x55c22bc50596 in decltype(std::__1::forward<void (*&)(Span<unsigned char const>)>(fp)(std::__1::forward<Span<unsigned char const> >(fp0))) std::__1::__invoke<void (*&)(Span<unsigned char const>), Span<unsigned char const> >(void (*&)(Span<unsigned char const>), Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/type_traits:3679:1
    #8 0x55c22bc50491 in void std::__1::__invoke_void_return_wrapper<void>::__call<void (*&)(Span<unsigned char const>), Span<unsigned char const> >(void (*&)(Span<unsigned char const>), Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/__functional_base:348:9
    #9 0x55c22bc503e1 in std::__1::__function::__alloc_func<void (*)(Span<unsigned char const>), std::__1::allocator<void (*)(Span<unsigned char const>)>, void (Span<unsigned char const>)>::operator()(Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/functional:1558:16
    #10 0x55c22bc4d6cb in std::__1::__function::__func<void (*)(Span<unsigned char const>), std::__1::allocator<void (*)(Span<unsigned char const>)>, void (Span<unsigned char const>)>::operator()(Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/functional:1732:12
    #11 0x55c22ccbff65 in std::__1::__function::__value_func<void (Span<unsigned char const>)>::operator()(Span<unsigned char const>&&) const /usr/local/bin/../include/c++/v1/functional:1885:16
    #12 0x55c22ccb8ff5 in std::__1::function<void (Span<unsigned char const>)>::operator()(Span<unsigned char const>) const /usr/local/bin/../include/c++/v1/functional:2560:12
    #13 0x55c22ccb8d61 in LLVMFuzzerTestOneInput /src/bitcoin-core/src/test/fuzz/fuzz.cpp:82:5
    #14 0x55c22bb4dd93 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
    #15 0x55c22bb39212 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6
    #16 0x55c22bb3eee7 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9
    #17 0x55c22bb68b52 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #18 0x7f65ab3ce83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #19 0x55c22bb14598 in _start (/out/coins_view+0x70c598)

DEDUP_TOKEN: raise--abort--
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x35438) in raise
==13==ABORTING






# python infra/helper.py reproduce $PROJECT_NAME coins_view ./download\?testcase_id\=6289089386119168  
Running: docker run --rm --privileged -i -v /root/oss-fuzz/build/out/bitcoin-core:/out -v '/root/oss-fuzz/download?testcase_id=6289089386119168:/testcase' -t gcr.io/oss-fuzz-base/base-runner reproduce coins_view -runs=100
+ FUZZER=coins_view
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer coins_view -runs=100 /testcase
/out/coins_view -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 483241304
INFO: Loaded 1 modules   (177730 inline 8-bit counters): 177730 [0x55caab469b68, 0x55caab4951aa), 
INFO: Loaded 1 PC tables (177730 PCs): 177730 [0x55caab4951b0,0x55caab74b5d0), 
/out/coins_view: Running 1 inputs 100 time(s) each.
Running: /testcase
coins_view: test/fuzz/coins_view.cpp:240: auto coins_view_fuzz_target(FuzzBufferType)::(anonymous class)::operator()() const: Assertion `MoneyRange(tx_fee_out)' failed.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==13==ERROR: AddressSanitizer: ABRT on unknown address 0x00000000000d (pc 0x7f65707cd438 bp 0x55caaa9d5420 sp 0x7fff8acbf8c8 T0)
SCARINESS: 10 (signal)
    #0 0x7f65707cd438 in raise (/lib/x86_64-linux-gnu/libc.so.6+0x35438)
    #1 0x7f65707cf039 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37039)
    #2 0x7f65707c5be6  (/lib/x86_64-linux-gnu/libc.so.6+0x2dbe6)
    #3 0x7f65707c5c91 in __assert_fail (/lib/x86_64-linux-gnu/libc.so.6+0x2dc91)
    #4 0x55caa97d10ab in coins_view_fuzz_target(Span<unsigned char const>)::$_12::operator()() const /src/bitcoin-core/src/test/fuzz/coins_view.cpp:240:17
    #5 0x55caa97beb4f in void CallOneOf<coins_view_fuzz_target(Span<unsigned char const>)::$_10, coins_view_fuzz_target(Span<unsigned char const>)::$_11, coins_view_fuzz_target(Span<unsigned char const>)::$_12, coins_view_fuzz_target(Span<unsigned char const>)::$_13, coins_view_fuzz_target(Span<unsigned char const>)::$_14, coins_view_fuzz_target(Span<unsigned char const>)::$_15, coins_view_fuzz_target(Span<unsigned char const>)::$_16>(FuzzedDataProvider&, coins_view_fuzz_target(Span<unsigned char const>)::$_10, coins_view_fuzz_target(Span<unsigned char const>)::$_11, coins_view_fuzz_target(Span<unsigned char const>)::$_12, coins_view_fuzz_target(Span<unsigned char const>)::$_13, coins_view_fuzz_target(Span<unsigned char const>)::$_14, coins_view_fuzz_target(Span<unsigned char const>)::$_15, coins_view_fuzz_target(Span<unsigned char const>)::$_16) /src/bitcoin-core/src/./test/fuzz/util.h:47:34
    #6 0x55caa97bd8fa in coins_view_fuzz_target(Span<unsigned char const>) /src/bitcoin-core/src/test/fuzz/coins_view.cpp:192:9
    #7 0x55caa96e0596 in decltype(std::__1::forward<void (*&)(Span<unsigned char const>)>(fp)(std::__1::forward<Span<unsigned char const> >(fp0))) std::__1::__invoke<void (*&)(Span<unsigned char const>), Span<unsigned char const> >(void (*&)(Span<unsigned char const>), Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/type_traits:3679:1
    #8 0x55caa96e0491 in void std::__1::__invoke_void_return_wrapper<void>::__call<void (*&)(Span<unsigned char const>), Span<unsigned char const> >(void (*&)(Span<unsigned char const>), Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/__functional_base:348:9
    #9 0x55caa96e03e1 in std::__1::__function::__alloc_func<void (*)(Span<unsigned char const>), std::__1::allocator<void (*)(Span<unsigned char const>)>, void (Span<unsigned char const>)>::operator()(Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/functional:1558:16
    #10 0x55caa96dd6cb in std::__1::__function::__func<void (*)(Span<unsigned char const>), std::__1::allocator<void (*)(Span<unsigned char const>)>, void (Span<unsigned char const>)>::operator()(Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/functional:1732:12
    #11 0x55caaa74ff65 in std::__1::__function::__value_func<void (Span<unsigned char const>)>::operator()(Span<unsigned char const>&&) const /usr/local/bin/../include/c++/v1/functional:1885:16
    #12 0x55caaa748ff5 in std::__1::function<void (Span<unsigned char const>)>::operator()(Span<unsigned char const>) const /usr/local/bin/../include/c++/v1/functional:2560:12
    #13 0x55caaa748d61 in LLVMFuzzerTestOneInput /src/bitcoin-core/src/test/fuzz/fuzz.cpp:82:5
    #14 0x55caa95ddd93 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
    #15 0x55caa95c9212 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6
    #16 0x55caa95ceee7 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9
    #17 0x55caa95f8b52 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #18 0x7f65707b883f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #19 0x55caa95a4598 in _start (/out/coins_view+0x70c598)

DEDUP_TOKEN: raise--abort--
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x35438) in raise
==13==ABORTING
```

</details>


I'll keep poking at this and update when I find more details.

**Comment by MarcoFalke** [comment]
This is not reproducible because it is an uninitialized read. Only the memory sanitizer or valgrind can detect this.

**Comment by MarcoFalke** [comment]
Left an idea at #5836

**Comment by MarcoFalke** [comment]
Msan reproduced this bug with the "correct" crash type here: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34843
