### ISSUE TITLE
Coverage reports not being found/linked to by clusterfuzz

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#7188]
January 19th seems to be the last day this worked: https://oss-fuzz.com/fuzzer-stats?project=libpng&fuzzer=libFuzzer_libpng_read_fuzzer&job=libfuzzer_asan_libpng&group_by=by-day
@Navidem I wonder if it's the recent build infra changes causing this.  Need to check ClusterFuzz side changes.
Note that I don't think coverage reports are totally broken. See https://storage.googleapis.com/oss-fuzz-coverage/libpng/reports/20220126/linux/report.html for example.

**Comment by jonathanmetzman** [comment]
After investigating, @Navidem figured out that the clusterfuzz code for saving coverage stats/links reads every file in the directory and assumes it is a stats file: https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/fuzzer_coverage.py#L115

**Comment by evverx** [comment]
@jonathanmetzman I wonder if it could be related to links to corpora pointing to pages like https://console.cloud.google.com/storage/systemd-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/systemd_fuzz-dhcp-server
![Screenshot 2022-01-27 at 22 31 06](https://user-images.githubusercontent.com/10195800/151430307-2625b43f-9408-4a8c-a05b-308e64653a97.png)

I clicked the "corpus backup" links at https://oss-fuzz.com/fuzzer-stats?group_by=by-day&fuzzer=libFuzzer_systemd_fuzz-dhcp-server&job=libfuzzer_asan_systemd&project=systemd

**Comment by jonathanmetzman** [comment]
This still seems to be happening, and I'm not sure why.

**Comment by oliverchang** [comment]
The link format changed. This was fixed by https://github.com/google/clusterfuzz/pull/2544, but we haven't deployed it yet. Doing that now.

**Comment by oliverchang** [comment]
Now deployed and fixed!

**Comment by kjlubick** [comment]
Still seeing this https://oss-fuzz.com/coverage-report/job/libfuzzer_asan_skia/latest expands to https://storage.googleapis.com/oss-fuzz-coverage/skia/reports/20230213/linux/report.html
