### ISSUE TITLE
fuchsia build is broken

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#792]
As per https://oss-fuzz-build-logs.storage.googleapis.com/index.html:

```
Step #3: [279/280] STAMP obj/packages/gn/mkbootfs.stamp
Step #3: [280/280] STAMP obj/packages/gn/default.stamp
Step #3: + cp out/debug-x86-64/host_x64/fidl-fuzzer /workspace/out/address/fuchsia_fidl_fuzzer
Step #3: cp: cannot stat 'out/debug-x86-64/host_x64/fidl-fuzzer': No such file or directory
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/fuchsia_fidl" failed: exit status 1
```

//cc @farahhariri

**Comment by farahhariri** [comment]
Looking at https://fuchsia.googlesource.com/fidl/+/master/BUILD.gn
It seems that the built of the fuzzer has been disabled for an upgrade of the toolchain.

**Comment by petrhosek** [comment]
This was caused by the libFuzzer move to compiler-rt, I'll try to roll out a new toolchain today which should resolve this issue.

**Comment by Dor1s** [comment]
Another build error now (https://oss-fuzz-build-logs.storage.googleapis.com/index.html):

```
...
Step #3: Updating all projects
Step #3: project.go:107: open /tmp/jiri-load846979121/manifest_ad81d9e784efd6cc/fidl: no such file or directory, project.go:107: open /tmp/jiri-load884343260/manifest_ad81d9e784efd6cc/fidl: no such file or directory
Step #3: WARN: import "manifest" not found locally, getting from server.
Step #3: 
Step #3: ERROR: while updation: Failed 1 times in a row. Last error:
Step #3: project.go:107: open /tmp/jiri-load846979121/manifest_ad81d9e784efd6cc/fidl: no such file or directory, project.go:107: open /tmp/jiri-load884343260/manifest_ad81d9e784efd6cc/fidl: no such file or directory, while writing history: project.go:107: open /tmp/jiri-load840899467/manifest_ad81d9e784efd6cc/fidl: no such file or directory
Finished Step #3
ERROR
```

**Comment by oliverchang** [comment]
This is still failing. @petrhosek any chance you could take another look?

**Comment by Dor1s** [comment]
Any progress here?

The build is still failing: https://oss-fuzz-build-logs.storage.googleapis.com/index.html

Should we disable it for now?

**Comment by Dor1s** [comment]
The build is still failing: https://oss-fuzz-build-logs.storage.googleapis.com/index.html

@petrhosek, friendly ping

**Comment by Dor1s** [comment]
Petr replied over email that it's currently blocked on  https://reviews.llvm.org/D37631.

**Comment by inferno-chromium** [comment]
@petrhosek, friendly ping

**Comment by Dor1s** [comment]
The build is still broken.

https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #3: + /src/fuchsia/.jiri_root/bin/jiri update
Step #3: WARN: Please opt in or out of analytics collection. You will receive this warning until an option is selected.
Step #3: To check what data we collect run 'jiri init -show-analytics-data'
Step #3: To opt-in run 'jiri init -analytics-opt=true "/src/fuchsia"'
Step #3: To opt-out run 'jiri init -analytics-opt=false "/src/fuchsia"'
Step #3: 
Step #3: Updating all projects
Step #3: WARN: import "manifest" not found locally, getting from server.
Step #3: 
Step #3: ERROR: while updation: Unable to get manifest file for /tmp/jiri-load847614058/manifest_ad81d9e784efd6cc origin/master:fidl, 'git show origin/master:fidl' failed:
Step #3: fatal: Path 'fidl' does not exist in 'origin/master'
Step #3: , Unable to get manifest file for /tmp/jiri-load521897153/manifest_ad81d9e784efd6cc origin/master:fidl, 'git show origin/master:fidl' failed:
Step #3: fatal: Path 'fidl' does not exist in 'origin/master'
Step #3: , while writing history: Unable to get manifest file for /tmp/jiri-load197277996/manifest_ad81d9e784efd6cc origin/master:fidl, 'git show origin/master:fidl' failed:
Step #3: fatal: Path 'fidl' does not exist in 'origin/master'
Step #3: 
```

**Comment by Dor1s** [comment]
Pinged @petrhosek over email.

**Comment by Dor1s** [comment]
@petrhosek  ping.

**Comment by Dor1s** [comment]
ping @petrhosek

**Comment by inferno-chromium** [comment]
i removed fuchsia_fidl for now, we can reinstantiate once we have better fuzz targets.
